name: e_commerce_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-164.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.1
  http: ^1.2.1
  dart_jsonwebtoken: ^2.14.0
  image_picker: ^1.1.1
  path: ^1.9.0
  dropdown_button2: ^2.3.9
  provider: ^6.1.2
  flutter_rating_bar: ^4.0.1
  flutter_web_data_table: ^1.0.0
  input_quantity: ^2.3.2
  image_picker_for_web: ^3.0.4
  mime: ^1.0.0
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
